### ISSUE TITLE
Remove recently added !important statements

### ISSUE THREAD

**Issue by kujenga** [rastech/website#55]
@wsvincent It looks like a recent PR brought in a bunch of `!important` statements to new scss files. Let's resolve whatever issues made them necessary and remove them.

**Comment by wsvincent** [comment]
@kujenga Yes, agree that was sloppy on my part. I'll fix...

**Comment by wsvincent** [comment]
@kujenga https://github.com/rastech/website/pull/56

**Comment by jasonbriggs** [comment]
This was resolved in that PR. Nice work!
